#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
name=$(basename ${dir})

docker rm -f ${name} 2>/dev/null
docker run -it -v "${dir}/shared:/shared" --name ${name} "$@" ${name}
